-- Insertar usuario con contraseña igual a 12345678
INSERT INTO usuarios(email, password, nombres, apellidos) VALUES
('dymm.latino4@gmail.com', '$2y$10$J9.lJOsrHohhhtZP1ps3uG69KPQ.98vIS1wTwntQ.JkEK26g3XslK', 'Darlin Yeilin', 'Melgarejo Miranda');

-- Insertar portafolio
INSERT INTO portafolios(usuario_id, nombre_completo, descripcion) VALUES
(1, 'Darlin Yeilin Melgarejo Miranda', 'Soy un desarrollador web apasionado por crear experiencias digitales únicas y funcionales. Con más de 5 años de experiencia en el campo, me especializo en tecnologías frontend y tengo un ojo agudo para el diseño y la usabilidad. Mi enfoque está en crear aplicaciones web interactivas y accesibles que no solo resuelvan problemas, sino que también ofrezcan una experiencia de usuario intuitiva y agradable. A lo largo de los años, he trabajado en una variedad de proyectos, desde sitios web corporativos hasta aplicaciones complejas para empresas de tecnología, y siempre estoy buscando nuevas formas de innovar y mejorar mis habilidades en el desarrollo de software. Estoy comprometido con el aprendizaje continuo, siempre al día con las últimas tendencias en desarrollo web, como el uso de frameworks modernos como React, Vue.js y tecnologías como Node.js para el desarrollo de aplicaciones robustas y escalables. Mi objetivo es transformar ideas en soluciones digitales que sean tanto funcionales como estéticamente agradables.');

-- Insertar skills
INSERT INTO skills (portafolio_id, nombre, descripcion) VALUES 
(1, 'JavaScript', 'Desarrollo de aplicaciones interactivas y dinámicas utilizando JavaScript, el lenguaje de programación más popular en la web. He trabajado con JavaScript puro, pero también con frameworks modernos como React.js y Vue.js para crear interfaces de usuario altamente interactivas y reactivas. Desde animaciones y efectos visuales hasta la creación de aplicaciones de una sola página (SPA), JavaScript es la herramienta clave para ofrecer experiencias de usuario fluidas y sin interrupciones. Además, tengo experiencia en el uso de bibliotecas como jQuery y Moment.js, y he implementado patrones de diseño como MVC para mantener el código organizado y escalable.'),
(1, 'HTML/CSS', 'Maquetación semántica y diseño responsivo utilizando HTML5 y CSS3. Mi enfoque en la creación de páginas web accesibles y bien estructuradas asegura que cada página sea fácil de navegar, tanto en dispositivos de escritorio como móviles. Utilizo técnicas de diseño responsivo, como Flexbox y CSS Grid, para asegurar que todos los elementos de la página se adapten correctamente a cualquier tamaño de pantalla. También presto atención a la accesibilidad web, garantizando que las páginas sean fáciles de usar para personas con discapacidades, utilizando buenas prácticas como etiquetas semánticas, descripciones alt y contraste adecuado en los colores.'),
(1, 'React', 'Creación de interfaces de usuario modernas y eficientes con React.js, uno de los frameworks más populares para construir aplicaciones de una sola página. React permite crear interfaces rápidas y reutilizables mediante componentes que gestionan su propio estado. He trabajado en diversos proyectos utilizando React, implementando funcionalidades como enrutamiento con React Router, manejo de formularios con Formik, y optimización del rendimiento con técnicas como la carga perezosa (lazy loading) y la memoización de componentes. Además, utilizo herramientas como Redux para la gestión del estado global y Axios para realizar solicitudes HTTP a servidores.'),
(1, 'Node.js', 'Desarrollo de APIs RESTful y aplicaciones de servidor con Node.js, un entorno de ejecución basado en JavaScript que permite crear aplicaciones escalables y rápidas. He utilizado Node.js para desarrollar APIs que interactúan con bases de datos y permiten el intercambio de datos entre el cliente y el servidor de manera eficiente. Además, implemento seguridad en las aplicaciones utilizando autenticación con JWT (JSON Web Tokens) y encriptación de contraseñas mediante bcrypt. También he trabajado con Express.js, un framework de Node.js, para crear servidores rápidos y ligeros que manejan solicitudes HTTP y gestionan rutas de manera eficiente.');

-- Insertar servicios
INSERT INTO servicios (portafolio_id, nombre, descripcion) VALUES
(1, 'Desarrollo Frontend', 'Ofrezco soluciones de desarrollo frontend enfocadas en crear interfaces de usuario dinámicas, interactivas y visualmente atractivas. Utilizo tecnologías modernas como React, Vue.js y Angular, para crear aplicaciones web rápidas y fáciles de usar. A través de la integración de diseño responsivo, garantizo que las aplicaciones se vean y funcionen perfectamente en cualquier dispositivo, desde móviles hasta pantallas grandes. Además, me enfoco en optimizar el rendimiento de las aplicaciones, asegurando tiempos de carga rápidos y experiencias de usuario sin interrupciones.'),
(1, 'Desarrollo Backend', 'Desarrollo de soluciones backend escalables y seguras utilizando Node.js, Express.js y otras tecnologías de servidor. Me especializo en crear APIs RESTful que permiten la integración eficiente de servicios y aplicaciones. Trabajo con bases de datos como MySQL, PostgreSQL y MongoDB para almacenar y recuperar datos de manera eficiente. También implemento medidas de seguridad, como autenticación y autorización con JWT, para asegurar que las aplicaciones sean robustas y seguras. Mi enfoque es crear sistemas backend que soporten un alto volumen de tráfico y ofrezcan una experiencia de usuario fluida y sin fallos.'),
(1, 'Optimización de Rendimiento', 'Realizo auditorías de rendimiento para identificar cuellos de botella en aplicaciones web y mejorar la velocidad de carga de las páginas. Utilizo herramientas como Lighthouse y Google PageSpeed Insights para evaluar el rendimiento y realizar mejoras en áreas clave, como la compresión de imágenes, la minimización de archivos JavaScript y CSS, y la implementación de estrategias de carga perezosa. También optimizo el rendimiento de la base de datos y la lógica del servidor para garantizar tiempos de respuesta rápidos, incluso con un gran volumen de datos. El objetivo es ofrecer una experiencia de usuario fluida y rápida, reduciendo las tasas de rebote y mejorando la conversión en sitios web comerciales.');

-- Insertar trabajos desarrollados
INSERT INTO trabajos_desarrollados (portafolio_id, nombre, descripcion, url_foto_trabajo, url_trabajo_github, url_trabajo_desplegado) VALUES
(1, 'Aplicación de Gestión de Tareas', 'Una aplicación web innovadora para la gestión de tareas y proyectos, diseñada para facilitar la organización personal y en equipo. Con una interfaz de usuario intuitiva y un flujo de trabajo optimizado, esta aplicación permite a los usuarios crear, editar y eliminar tareas, asignar prioridades y fechas de vencimiento, y llevar un seguimiento del progreso. Utilizando React para la interfaz de usuario y Node.js en el backend, la aplicación se integra con bases de datos como MongoDB para almacenar las tareas de manera eficiente. Además, la aplicación incluye notificaciones en tiempo real, permitiendo a los usuarios mantenerse al tanto de sus tareas y plazos. La aplicación está optimizada para ser utilizada en dispositivos móviles y de escritorio, y se implementaron medidas de seguridad para proteger los datos de los usuarios.', 'assets/images/placeholder-image.jpg', 'https://github.com/darlin/tareas-app', 'https://tareasapp.com'),
(1, 'Portfolio Personal', 'Este es mi portafolio personal donde muestro una selección de proyectos en los que he trabajado. El sitio web fue diseñado para ser una representación interactiva de mis habilidades como desarrollador web, y presenta tanto mis proyectos de desarrollo frontend como backend. La interfaz es completamente responsiva y se adapta a todos los dispositivos, desde computadoras de escritorio hasta teléfonos móviles. Además, incluye enlaces a mis perfiles de GitHub, LinkedIn y otros recursos en línea, lo que permite a los visitantes explorar más sobre mi trabajo y mi experiencia. El backend fue desarrollado en Node.js, y el sitio se conecta a una base de datos MongoDB para almacenar datos sobre mis proyectos. El objetivo principal de este portafolio es destacar mis habilidades técnicas y mi capacidad para crear soluciones digitales elegantes y funcionales.', 'assets/images/placeholder-image.jpg', 'https://github.com/darlin/portfolio', 'https://darlin.dev');

-- Insertar contactos
INSERT INTO contactos (portafolio_id, tipo_contacto, enlace_contacto, titulo_enlace) VALUES
(1, 'email', 'dymm.latino4@gmail.com', 'No dudes en enviarme un correo si tienes alguna pregunta sobre mis proyectos o te interesa trabajar conmigo.'),
(1, 'linkedin', 'https://www.linkedin.com/in/darlin-yeilin', 'Conéctate conmigo en LinkedIn para seguir mis actualizaciones profesionales.'),
(1, 'github', 'https://github.com/darlin', 'Echa un vistazo a mi perfil de GitHub para explorar algunos de mis proyectos.');
